apiVersion: v1
kind: DaemonSet
metadata:
  name: infra-api-daemonset
spec:
  selector:
    matchLabels:
      name: infra-api
  template:
    metadata:
      labels:
        name: infra-api
    spec:
      containers:
      - name: infra-api
        image: infra-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: host-system-info-volume
          mountPath: /host-data
          readOnly: true
      volumes:
      - name: host-system-info-volume
        hostPath:
          path: /home/admin/batch/log
