apiVersion: v1
kind: Pod
metadata:
  name: infra-api
spec:
  nodeName: kind-worker3
  containers:
  - name: infra-api
    image: infra-api:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 80
    volumeMounts:
    - name: host-system-info-volume
      mountPath: /host-data
    - name: host-proc-volume
      mountPath: /host-proc
  volumes:
  - name: host-system-info-volume
    hostPath:
      path: /root
  - name: host-proc-volume
    hostPath:
      path: /proc
